### ISSUE TITLE
Change-Me's Need to be Consistent

### ISSUE THREAD

**Issue by lee-coriell** [PacketFabric/terraform-provider-packetfabric#120]
Not a big deal, but in this [file](https://github.com/PacketFabric/terraform-provider-packetfabric/blob/dev/examples/variables.tf) it would help to be consistent with the "change me" as sometimes we have it listed as "change me", "change-me" and some others "changeme".

Also I think we may have missed a few "change-me" 's like:
Line #22:  default = 123456789
Line #122:  default = "123456789abcdef123456789abcdef12"
Line# 213: default = "0d5225a8-f000-47ee-b3ea-64888f6d5da9"

I also like when we show options in the comments, like:
default  = 65000 # PacketFabric ASN 4556
default = "1Gbps" # 100Mbps / 10Gbps
default = ["US"] # ["UK"] ["US", "UK"]
default = true # True == Allow longer subnet prefixes / False == Exact subnet matching
as examples...

**Comment by rjouhann** [comment]
I have updated the examples folder quite a bit. See details in the PR https://github.com/PacketFabric/terraform-provider-packetfabric/pull/121
