### ISSUE TITLE
Add Contacts API support

### ISSUE THREAD

**Issue by medzin** [PacketFabric/terraform-provider-packetfabric#13]
Adding support for Packetfabric Contacts API via Terraform resources and data sources would allow managing billing information via Terraform.

API docs: https://docs.packetfabric.com/api/v2/redoc/#tag/Contacts

**Comment by elXaptation** [comment]
@medzin support for Packetfabric Contacts is scheduled for Stage-4 Feature release (v0.4.0). Currently you've been playing with Stage-1 features. Stage-4 is features are a few (4) Weeks out. Closing this issue.

**Comment by elXaptation** [comment]
Please close.
