### ISSUE TITLE
More meaningful examples of resources usage

### ISSUE THREAD

**Issue by medzin** [PacketFabric/terraform-provider-packetfabric#14]
Current examples of all resource usage are not very representative - they just assign values from variables, and the examples should contain the values similar to when someone will write the actual code. Below is an example cloud router that represents resource usage more than the one in the current documentation.

```hcl
resource "cloud_router" "router" {
  provider     = packetfabric
  scope        = "private"
  asn          = "1234"
  name         = "Router A"
  account_uuid = "484eece8-f889-11ec-b939-0242ac120002"
  capacity     = "100Mbps"
  regions      = ["US"]
}
```

**Comment by elXaptation** [comment]
@medzin all the vars in the examples are defined in the examples/variables.tf file. Do you still want actual values in the example giving the variables.tf file?

**Comment by rjouhann** [comment]
Ideally, I think it makes sense to give actual values as examples in the variable file and keep the main.tf file only with variables. I would just use the same example values from the API spec

**Comment by medzin** [comment]
@rjouhann @elXaptation I meant the examples in the documentation (`.md` files), not in the code. In the Terraform registry (https://registry.terraform.io/), I will only see what is in the documentation, not the entire repository. It will be inconvenient to switch back and forth between the repo and registry to see what the values are in the example.

**Comment by rjouhann** [comment]
@freeform700 is going to help with the docs on the registry.

**Comment by elXaptation** [comment]
> @rjouhann @elXaptation I meant the examples in the documentation (`.md` files), not in the code. In the Terraform registry (https://registry.terraform.io/), I will only see what is in the documentation, not the entire repository. It will be inconvenient to switch back and forth between the repo and registry to see what the values are in the example.

Good point.. the registry docs can't see the entire repo.. I think real values is the right way to go.

**Comment by rjouhann** [comment]
Values from https://docs.packetfabric.com/api/v2/redoc should be good to use.

**Comment by rjouhann** [comment]
I updated variable.tf with good values as examples
