### ISSUE TITLE
BGP for an Azure session using primary_subnet and/or secondary_subnet

### ISSUE THREAD

**Issue by rjouhann** [PacketFabric/terraform-provider-packetfabric#163]
**[Romain] I think I fixed it but please, review my changes in the BGP session go files.**

When trying to setup BGP for an Azure session using `primary_subnet` and/or `secondary_subnet`, I am getting the following error:

```
│ Error: Status: 400, body: {"message": "InvalidParam: l3_address, primary_subnet or secondary_subnet is required.", "request_id": "11f14f06-ecd9-4b90-95f0-d23d91e69faf"}
│ 
│   with packetfabric_cloud_router_bgp_session.crbs_2,
│   on main.tf line 238, in resource "packetfabric_cloud_router_bgp_session" "crbs_2":
│  238: resource "packetfabric_cloud_router_bgp_session" "crbs_2" {

```

Terraform config:
```
resource "packetfabric_cloud_router_bgp_session" "crbs_2" {
  provider         = packetfabric
  circuit_id       = packetfabric_cloud_router.cr.id
  connection_id    = packetfabric_cloud_router_connection_azure.crc_2.id
  address_family   = var.pf_crbs_af
  multihop_ttl     = var.pf_crbs_mhttl
  remote_asn       = var.azure_side_asn1
  orlonger         = var.pf_crbs_orlonger
  primary_subnet   = var.azure_primary_peer_address_prefix
  secondary_subnet = var.azure_secondary_peer_address_prefix
}
```

**Comment by pontovinte** [comment]
@rjouhann, does this condition applies to Azure only?
I'm not sure if I'm following what's expected by the server in this case.

**Comment by rjouhann** [comment]
Yes this is for Azure Cloud Router only, I added the missing parameter in the BGP resource and I tested it, things works fine. I just wanted to confirm the code I added was good. Here was my commit https://github.com/PacketFabric/terraform-provider-packetfabric/pull/150/commits/46bb5f007915bdee3616a665363fafb047702576#diff-f72c174773553c0189b2c9be7f74fdcaaaa7645751d658f668f06d097a0d856d.
