### ISSUE TITLE
Wait till packetfabric_point_to_point is active

### ISSUE THREAD

**Issue by medzin** [PacketFabric/terraform-provider-packetfabric#171]
Terraform should wait during `packetfabric_point_to_point` resource creation until it becomes active (it can be checked via this endpoint https://docs.packetfabric.com/api/v2/redoc/#tag/PTP-Services/operation/getptp). Otherwise, the user will get an error when they try to modify it.

**Comment by pontovinte** [comment]
@rjouhann or @medzin, can you please specify the desired state returned from the API above? Is it `COMPLETE`?

**Comment by rjouhann** [comment]
This would be the API to use to check the state:

[/v2.1/services/point-to-point/{ptp_circuit_id}/status](https://docs.packetfabric.com/api/v2/swagger/#/PTP%20Services/ptpstatus2_1)

I think the logic should be the same as [/v2.1/services/{vc_circuit_id}/status](https://docs.packetfabric.com/api/v2/swagger/#/Services/vcstatus_2_1)
