### ISSUE TITLE
Wait till packetfabric_backbone_virtual_circuit is active

### ISSUE THREAD

**Issue by rjouhann** [PacketFabric/terraform-provider-packetfabric#172]
We should update the way we check the resource creation is completed. Right now, the resource show completed almost right away while the VC is still under provisioning. We need to update the logic to check the status of VC creation and only mark the resource complete when ``state: "COMPLETE"`` (I think this would be something to add in ``aws_backbone.go``).

```
{
    "state":"COMPLETE",
    "description":"Complete"
}
```

**Comment by pontovinte** [comment]
@rjouhann, are you talking about this state here?
![image](https://user-images.githubusercontent.com/72367088/198632872-59df1fd9-e4be-4d89-9a7c-14d8c1566a1c.png)

**Comment by rjouhann** [comment]
No, here we are talking about a backbone virtual circuit, the screenshot above is for a marketplace VC.

[/v2/services/backbone](https://docs.packetfabric.com/api/v2/swagger/#/Services/post_service_backbone)

<img width="818" alt="Screenshot 2022-10-28 at 07 18 47" src="https://user-images.githubusercontent.com/25542366/198640493-8d9815d4-46b4-43bd-93e8-e86ff92602aa.png">

When you create the VC, terraform doesn't check the state so it shows the resource is completed while it is actually not (it takes ~30s to create a VC most of the time).
