### ISSUE TITLE
packetfabric_cloud_router_connection_ipsec: accept null value for phase2_authentication_algo

### ISSUE THREAD

**Issue by rjouhann** [PacketFabric/terraform-provider-packetfabric#192]
We need to change ``packetfabric_cloud_router_connection_ipsec`` to accept `null` for ``phase2_authentication_algo`` attribute. 

Or make `phase2_authentication_algo` optional but send `null` value if no present.

Body
```
{
  "description": "Test description",
  "account_uuid": "0d3b7d1f-9596-4d83-9f7f-b160f699784b",
  "pop": "DAL1",
  "speed": "100Mbps",
  "ike_version": 1,
  "phase1_authentication_method": "pre-shared-key",
  "phase1_group": "group14",
  "phase1_encryption_algo": "3des-cbc",
  "phase1_authentication_algo": "sha-384",
  "phase1_lifetime": 10800,
  "phase2_pfs_group": "group14",
  "phase2_encryption_algo": "aes-128-gcm",
  "phase2_authentication_algo": null,
  "phase2_lifetime": 28800,
  "gateway_address": "123.43.23.2",
  "shared_key": "superCoolKey"
}
```

Response:
```
{
    "circuit_id": "PF-IPSEC-1749778",
    "customer_gateway_address": "123.43.23.2",
    "local_gateway_address": "23.159.0.138",
    "ike_version": 1,
    "phase1_authentication_method": "pre-shared-key",
    "phase1_group": "group14",
    "phase1_encryption_algo": "3des-cbc",
    "phase1_authentication_algo": "sha-384",
    "phase1_lifetime": 10800,
    "phase2_pfs_group": "group14",
    "phase2_encryption_algo": "aes-128-gcm",
    "phase2_authentication_algo": null,
    "phase2_lifetime": 28800,
    "pre_shared_key": "superCoolKey",
    "deleted": false,
    "time_created": "2022-10-26T09:44:32.663512-0600",
    "time_updated": "2022-10-26T09:44:32.663512-0600",
    "vc_circuit_id": "PF-L3-CON-1749779",
    "description": "Test description",
    "account_uuid": "0d3b7d1f-9596-4d83-9f7f-b160f699784b",
    "pop": "DAL1",
    "speed": "100Mbps"
}
```

**Comment by pontovinte** [comment]
@rjouhann, usually when the value is `NULL` we don't send the attribute as part of the payload. So, my question is: The attribute above MUST be send as `NULL` or not sending as part of the payload is ok?

**Comment by rjouhann** [comment]
There is a problem with the PF API initially. We should do what you said and simply make `phase2_authentication_algo` optional so we don't send it to the payload if it is null/not set.

We are planning to fix the PF API but in the meantime, sending the properties in the payload with `null` is the current workaround.

I have created another issue for when the API gets fixed later https://github.com/PacketFabric/terraform-provider-packetfabric/issues/193

If you think this is simple and possible, let's do this workaround for 0.3.2, it this makes it too complicated to implement, we can just wait for PF API to get fixed.

**Comment by rjouhann** [comment]
Upcoming PacketFabric release will make the attribute `phase2_authentication_algo` optional. It will also be optional in PacketFabric Terraform v0.3.2 release.
