### ISSUE TITLE
Not possible to setup BFD setting with cloud_router_bgp_session

### ISSUE THREAD

**Issue by rjouhann** [PacketFabric/terraform-provider-packetfabric#21]
Everything is in the title, see [docs](https://docs.packetfabric.com/cr/bgp/bgp_aws/)

_BFD settings
Select Enable BFD to enable Bidirectional Forwarding Detection (BFD) for this connection.

When BFD is enabled, test packets are periodically sent to BGP peers. If a peer fails to reply after a specified interval and number of attempts, the BGP session shuts down._

**Comment by pontovinte** [comment]
@rjouhann, can you please provide the `.yaml` file you used to reproduce this issue?
