### ISSUE TITLE
Use of dyanmic for setting prefixes in packetfabric_cloud_router_bgp_session does not correctly apply

### ISSUE THREAD

**Issue by kliu47** [PacketFabric/terraform-provider-packetfabric#213]
Use of dyanmic for setting prefixes in packetfabric_cloud_router_bgp_session does not correctly apply

terraform plan shows the update correctly but on apply, it does not correctly update the BGP session

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform PacketFabric Provider Version

Terraform v1.2.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.29.0
+ provider registry.terraform.io/hashicorp/google v4.39.0
+ provider registry.terraform.io/hashicorp/google-beta v4.34.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/time v0.8.0
+ provider registry.terraform.io/packetfabric/packetfabric v0.3.1

### Affected Resource(s)

* packetfabric_cloud_router_bgp_session

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "packetfabric_cloud_router_bgp_prefixes" "crbp_aws" {
  provider          = packetfabric
  bgp_settings_uuid = packetfabric_cloud_router_bgp_session.crbs_aws_shared_services.id
  prefixes {
    prefix = "10.0.0.0/8"
    type   = "out" # Allowed Prefixes from Cloud
    order  = 0
  }
  dynamic "prefixes" {
    for_each = local.tgw_association_allowed_prefixes
    content {
      prefix = prefixes.key
      type   = "in"
      order  = 0
    }
  }
}
```

### Expected Behavior

Prefixes are set/updated properly for the BGP session 

### Actual Behavior

Prefixes for BGP session are not updated

### Steps to Reproduce

1. `terraform apply`

**Comment by rjouhann** [comment]
Hello,

- packetfabric_cloud_router_bgp_prefixes maps to [/v2/bgp-settings/{bgp_settings_uuid}/prefixes](https://docs.packetfabric.com/api/v2/swagger/#/BGP%20Session%20Settings/bgp_prefixes_create)

- packetfabric_cloud_router_bgp_session maps to [/v2/services/cloud-routers/{circuit_id}/connections/{cloud_connection_circuit_id}/bgp](https://docs.packetfabric.com/api/v2/swagger/#/BGP%20Session%20Settings/cloud_routers_bgp_create)

You actually can't update the prefix through `packetfabric_cloud_router_bgp_prefixes` but only through `packetfabric_cloud_router_bgp_session`.

You can see the `/v2/bgp-settings/{bgp_settings_uuid}/prefixes` does not have a PUT or a PATCH.
However`/v2/services/cloud-routers/{circuit_id}/connections/{cloud_connection_circuit_id}/bgp` has the PUT allowing to update the prefixes.

Now, in v0.3.1 and lower of the PacketFabric Provider, you will notice terraform resource `packetfabric_cloud_router_bgp_session` doesn't have the prefix attribute.

We will be adding the missing attribute to the `packetfabric_cloud_router_bgp_session` resource in v0.3.2 planned for early next week (see https://github.com/PacketFabric/terraform-provider-packetfabric/issues/138).

Once v0.3.2 is available, you can update your code:

```
## From the PacketFabric side: Configure BGP
resource "packetfabric_cloud_router_bgp_session" "crbs_aws_shared_services" {
  provider       = packetfabric
  circuit_id     = packetfabric_cloud_router.cr1.id
  connection_id  = packetfabric_aws_cloud_router_connection.aws_shared_service_connection.id
  address_family = var.pf_crbs_af
  multihop_ttl   = var.pf_crbs_mhttl
  remote_asn     = var.aws_side_asn
  orlonger       = var.pf_crbs_orlonger
  remote_address = aws_dx_private_virtual_interface.direct_connect_vip_shared_service.amazon_address   # AWS side
  l3_address     = aws_dx_private_virtual_interface.direct_connect_vip_shared_service.customer_address # PF side
  md5            = aws_dx_private_virtual_interface.direct_connect_vip_shared_service.bgp_auth_key
  prefixes {
    prefix = "10.0.0.0/8"
    type   = "out" # Allowed Prefixes from Cloud
    order  = 0
  }
  dynamic "prefixes" {
    for_each = local.tgw_association_allowed_prefixes
    content {
      prefix = prefixes.key
      type   = "in"
      order  = 0
    }
  }
}
```
