### ISSUE TITLE
Handle cloud router deletion when billing is not created yet

### ISSUE THREAD

**Issue by medzin** [PacketFabric/terraform-provider-packetfabric#244]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is an edge case where if someone tries to delete the cloud router for which billing was not created, it will end with an error (e.g. acceptance testing). It may take up to a few minutes until billing is assigned. It will improve user experience if we wait with router deletion until the billing is set. The following API endpoint should be used to check if the billing is already set for the circuit ID:

https://docs.packetfabric.com/api/v2/redoc/#tag/Billing/operation/get_order

**Comment by rjouhann** [comment]
@medzin could we add a 30se delay in our testing between creation and deletion as a temporary workaround?

**Comment by rjouhann** [comment]
For now @medzin, could you handle this in the test case? 

Creating/Deleting a CR in a short amount of time isn't really a real customer scenario. We can improve the delete late one.

**Comment by medzin** [comment]
Added destroy delay in #282
