### ISSUE TITLE
Update/Improve CONTRIBUTING.md

### ISSUE THREAD

**Issue by rjouhann** [PacketFabric/terraform-provider-packetfabric#268]
As discussed, could we update/improve [CONTRIBUTING.md](https://github.com/PacketFabric/terraform-provider-packetfabric/blob/main/CONTRIBUTING.md) and add more insight on how the terraform provider is structured so it's easier for anyone to contribute.

My understanding:

1. you can find the mapping between `resources/data-sources` in the `internal/provider/provider.go` (e.g. `"packetfabric_cloud_router": resourceCloudRouter(),`)
2. Then the functions (e.g. `resourceCloudRouter()`) are defined in other go files in the same `internal/provider/folder`
3. Each functions reference to other functions to do the read/create/update/delete operations
The API/URI used along with the structure for both requests and responses are defined in `internal/packetfabric` folder (e.g. cloud_router.go is using /v2/services/cloud-routers URI, etc...)
4. Both resources and data-sources are using definition in `internal/packetfabric` folder

**Comment by elXaptation** [comment]
@rjouhann lets discuss this todo item. In the mean time, lets move out of v0.5.0. v1.0.0 maybe?
