### ISSUE TITLE
Add the Option to Use a Flex Bandwidth Bucket for a Backbone VC, Marketplace VC or an IX Virtual Circuit using Terraform Resources

### ISSUE THREAD

**Issue by lee-coriell** [PacketFabric/terraform-provider-packetfabric#319]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

PacketFabric has the ability to provide a Flex Bandwidth Bucket to buy VCs in bulk.   I would like the ability to add, upgrade or delete a  Backbone VC, Marketplace VC or an IX Virtual Circuit into a Flex Bandwidth Bucket using Terraform Resources.

### New or Affected Resource(s)

New
???

Affected
--[packetfabric_backbone_virtual_circuit](https://github.com/PacketFabric/terraform-provider-packetfabric/tree/main/examples/resources/packetfabric_backbone_virtual_circuit)
--[packetfabric_backbone_virtual_circuit_marketplace](https://github.com/PacketFabric/terraform-provider-packetfabric/tree/main/examples/resources/packetfabric_backbone_virtual_circuit_marketplace)
--[packetfabric_ix_virtual_circuit_marketplace](https://github.com/PacketFabric/terraform-provider-packetfabric/tree/main/examples/resources/packetfabric_ix_virtual_circuit_marketplace)
--[packetfabric_cs_aws_hosted_marketplace_connection](https://github.com/PacketFabric/terraform-provider-packetfabric/tree/main/examples/resources/packetfabric_cs_aws_hosted_marketplace_connection)
--[packetfabric_cs_azure_hosted_connection](https://github.com/PacketFabric/terraform-provider-packetfabric/tree/main/examples/resources/packetfabric_cs_azure_hosted_connection)
--[packetfabric_cs_google_hosted_marketplace_connection](https://github.com/PacketFabric/terraform-provider-packetfabric/tree/main/examples/resources/packetfabric_cs_google_hosted_marketplace_connection)
--[packetfabric_cs_oracle_hosted_marketplace_connection](https://github.com/PacketFabric/terraform-provider-packetfabric/tree/main/examples/resources/packetfabric_cs_oracle_hosted_marketplace_connection)

* packetfabric_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

**Comment by rjouhann** [comment]
@lee-coriell 

You can only use flex bandwidth for long-haul virtual circuits. These can be backbone virtual circuits, marketplace virtual circuits, or IX virtual circuits. It cannot be used for ports, point-to-point, or cloud services.

We will update:

--[packetfabric_backbone_virtual_circuit](https://github.com/PacketFabric/terraform-provider-packetfabric/tree/main/examples/resources/packetfabric_backbone_virtual_circuit)
--[packetfabric_backbone_virtual_circuit_marketplace](https://github.com/PacketFabric/terraform-provider-packetfabric/tree/main/examples/resources/packetfabric_backbone_virtual_circuit_marketplace)
--[packetfabric_ix_virtual_circuit_marketplace](https://github.com/PacketFabric/terraform-provider-packetfabric/tree/main/examples/resources/packetfabric_ix_virtual_circuit_marketplace)
