### ISSUE TITLE
Add Terraform Import support for IX Virtual Circuit

### ISSUE THREAD

**Issue by asteen27** [PacketFabric/terraform-provider-packetfabric#333]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

IX Virtual Circuit resource does not support `terraform import`

### New or Affected Resource(s)

* packetfabric_ix_virtual_circuit_marketplace

### Example: 

```shell
terraform import packetfabric_ix_virtual_circuit_marketplace.PF-IX-SFO-SFO-1234567

```

**Comment by rjouhann** [comment]
Hello @asteen27,

The resource `packetfabric_ix_virtual_circuit_marketplace` is used to make a [request to the IX provider](https://docs.packetfabric.com/eco/a/ix/). Once the request has been accepted, we should be able to import the virtual circuit using `packetfabric_backbone_virtual_circuit` resource and manage it from there (change the VLAN, upgrade the speed, etc..).

However, it won't work right now as the `interface_z` block is required. I will look into making necessary changes so it becomes optional and we can import the IX VC into Terraform.

I should be able to have something working by next week. Let me know if you have any questions.

Thanks & Regards,
Romain

**Comment by asteen27** [comment]
@rjouhann thanks! And kudos to you and the PacketFabric team for this provider in general. Our team loves having this all in Terraform!

**Comment by rjouhann** [comment]
Thanks for your feedback and also for opening the GitHub issue.

We made the necessary changes to the provider so you will be able to import an IX Virtual Circuit and manage it through Terraform.

https://user-images.githubusercontent.com/25542366/218988150-4c996029-bd3f-478a-94b2-511e11a481cf.mov

We still need to do some more testing/validation before releasing but `v1.0.4` should come either today or tomorrow!
