### ISSUE TITLE
Email address of order

### ISSUE THREAD

**Issue by sthakor-pf** [PacketFabric/terraform-provider-packetfabric#338]
One interesting thing I found out was if a service gets ordered via TerraForm it gets svc_packetfabric@... email alias as the originator. When ordered via portal it gets the user ID/email.

It would be great to have that as terraform_packetfabric@...
to clearly indicate it is being ordered via TerraForm.

**Comment by rjouhann** [comment]
Terrafom is using the PacketFabric API. Therefore, it is using an API key to authenticate. There are no email address or user attached to an API key.
There is nothing we can do in Terraform code but we could probably do something on the PacketFabric side to change the email used for API users.

**Comment by rjouhann** [comment]
@sthakor-pf let's follow up internally. Thanks!
