### ISSUE TITLE
Errors with "usage" based backbone virtual circuits

### ISSUE THREAD

**Issue by asteen27** [PacketFabric/terraform-provider-packetfabric#339]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* packetfabric_backbone_virtual_circuit

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

**main.tf** 
```hcl
terraform {
  required_version = "~> 1.2.0"

  required_providers {
    packetfabric = {
      source  = "PacketFabric/packetfabric"
      version = "1.0.4"
    }
  }
}

provider "packetfabric" {
  host = "https://api.packetfabric.com"
}
```

**virtual_circuits.tf**
```hcl
resource "packetfabric_backbone_virtual_circuit" "ix-import-1" {
  provider    = packetfabric
  description = <snip>
  epl         = false

  bandwidth {
    account_uuid      = var.pf_old_account_uuid
    longhaul_type     = "usage"
    speed             = "10Gbps"
    subscription_term = 0
  }

  interface_a {
    port_circuit_id = "<snip>"
    untagged        = false
    vlan            = 202
  }

  interface_z {
    port_circuit_id = "<snip>"
    untagged        = false
    vlan            = 5
  }
}
```

### Expected Behavior

`terraform apply` succeeds

### Actual Behavior

After running `terraform apply` we got multiple 400 errors:

* `Metro VCs do not support upgrades or renewals`
* `billing_product_type: This field is required.; subscription_term: This field is required.`

This is my attempt to import an IX circuit after the release of `1.0.4`. If I look at the state of the resource following the import, `subscription_term` is equal to `0`. `speed` is not shown either, but I added that since the provider required it.

I confirmed that by querying the API directly as well.

Our `dedicated` IX circuit worked fine, just not this `usage` based one.

### Steps to Reproduce

1. `terraform apply`

**Comment by rjouhann** [comment]
Thanks for reporting the bug. I didn't validate the usage based use case, my bad. I will get you a fix early next week.

**Comment by asteen27** [comment]
@rjouhann Thanks for fixing this! Looks like it worked!

I was mistaken when I said the `longhaul_type = dedicated` circuit worked, but I'll open a new issue for that when I get a sec.

**Comment by rjouhann** [comment]
`longhaul_type = dedicated` should work, I will look into it as soon as you open the new issue. Maybe this is something else I missed in the Terraform state import. I will get you a new fix for that new issue asap anyhow!
