### ISSUE TITLE
Error: Status: 400, Metro VCs do not support upgrades or renewals

### ISSUE THREAD

**Issue by asteen27** [PacketFabric/terraform-provider-packetfabric#350]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* packetfabric_backbone_virtual_circuit

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

**main.tf**
```hcl
terraform {
  required_version = "~> 1.2.0"

  required_providers {
    packetfabric = {
      source  = "PacketFabric/packetfabric"
      version = "1.0.6"
    }
  }
}

provider "packetfabric" {
  host = "https://api.packetfabric.com"
}
```

**virtual_circuits.tf**
```hcl
resource "packetfabric_backbone_virtual_circuit" "ix-import-2" {
  provider    = packetfabric
  description = <snip>
  epl         = false

  bandwidth {
    account_uuid      = var.pf_account_uuid
    longhaul_type     = "dedicated"
    speed             = "10Gbps"
    subscription_term = 1
  }

  interface_a {
    port_circuit_id = <snip>
    untagged        = false
    vlan            = 201
  }

  interface_z {
    port_circuit_id = <snip>
    untagged        = false
    vlan            = 1001
  }
}
```

### Expected Behavior

`terraform apply` succeeds

### Actual Behavior

After running `terraform apply` there was a 400 error:

* `Metro VCs do not support upgrades or renewals`

This resource was imported prior to running the `terraform apply`. The resource definition shown above matches what is shown in the `terraform state show` command so there shouldn't be anything actually being modified.

### Steps to Reproduce

1. `terraform apply`

**Comment by rjouhann** [comment]
@asteen27 could you share the output of your `terraform apply` (without answering `yes`).

It looks like the terraform update logic is getting triggered. In the provider code, the modify bandwidth call is made when there is a change in `bandwidth`.

Could you also share the ` "resources": []` of your `terraform.state` file? Especially the `bandwidth[]` block?

Thanks!

**Comment by rjouhann** [comment]
@asteen27 never mind, I found the problem. For Metro circuit, `longhaul_type` is missing the GET so the bandwidth block isn't getting imported properly. I will get you a fix asap.

**Comment by rjouhann** [comment]
@asteen27 I just pushed a `v1.0.7` with a fix. When you define your Metro VC in the Terraform config file, make sure you do not include `longhaul_type` which isn't needed for Metro VC.

It should look like this now and terraform import should work with `v1.0.7`.
```
resource "packetfabric_backbone_virtual_circuit" "ix-import-2" {
  provider    = packetfabric
  description = <snip>
  epl         = false

  bandwidth {
    account_uuid      = var.pf_account_uuid
    speed             = "10Gbps"
    subscription_term = 1
  }

  interface_a {
    port_circuit_id = <snip>
    untagged        = false
    vlan            = 201
  }

  interface_z {
    port_circuit_id = <snip>
    untagged        = false
    vlan            = 1001
  }
}
```
Let me know if you find any other problems.

Thanks & Regards,
Romain

**Comment by asteen27** [comment]
@rjouhann That worked! Thanks for the quick fix once again!
