### ISSUE TITLE
Missing usage example for cloud_services_aws_hosted_connection resource

### ISSUE THREAD

**Issue by medzin** [PacketFabric/terraform-provider-packetfabric#4]
`cloud_services_aws_hosted_connection` resource is missing usage example:

https://github.com/PacketFabric/terraform-provider-packetfabric/blob/dev/docs/resources/cloud_services_aws_hosted_connection.md#schema

**Comment by elXaptation** [comment]
Will update/provide with completion of #9

**Comment by rjouhann** [comment]
#9 closed so this one can be closed
