### ISSUE TITLE
Removed the scope attribute when creating a new Cloud Router

### ISSUE THREAD

**Issue by rjouhann** [PacketFabric/terraform-provider-packetfabric#40]
We just released a [new release](https://docs.packetfabric.com/releases/07_25/) of the platform and we have removed the scope attribute when creating a new Cloud Router. We'll need to update the terraform provider for that - it used to be required.
FYI, the API doesn't return an error if you specify scope, so currently attribute will be just ignored.

**Comment by rjouhann** [comment]
Includes also the example update under:

- https://github.com/PacketFabric/terraform-provider-packetfabric/blob/dev/examples/data-sources/packetfabric_cloud_router/data-source.tf
- https://github.com/PacketFabric/terraform-provider-packetfabric/blob/dev/examples/resources/packetfabric_cloud_router/resource.tf
- And all other examples that contains the scope attribute

**Comment by pontovinte** [comment]
Based on the description, this issue looks like an `enhancement`.

**Comment by rjouhann** [comment]
It would be great to remove the scope attribute for v0.2.0 as this attribute doesn't exist and is ignored now in PF platform.

**Comment by rjouhann** [comment]
@elXaptation let's do this in v0.3.0
