### ISSUE TITLE
cloud_router_bgp_session: NAT settings (prefixes and nat) documentation improvement

### ISSUE THREAD

**Issue by rjouhann** [PacketFabric/terraform-provider-packetfabric#43]
We don't give many details/examples today on how to set up NAT settings:

- prefixes | Array of objects
- nat | object

Especially, how do I add multiple prefixes?

Doc: https://docs.packetfabric.com/cr/bgp/bgp_ibm/

API ref:https://docs.packetfabric.com/api/v2/redoc/#tag/BGP-Session-Settings/operation/cloud_routers_bgp_create

Web Portal:
<img width="754" alt="Screen Shot 2022-07-28 at 13 37 34" src="https://user-images.githubusercontent.com/25542366/181634189-a74d48c5-0c29-405a-9866-e0b8591e5376.png">

**Comment by freeform700** [comment]
Added definitions when doing schema updates https://github.com/PacketFabric/terraform-provider-packetfabric/pull/67/files#diff-6fbd0967cc24bcb2bb4e0bad3d7f8dc36362ab8d2ef640b86d85b703a7df4996
