### ISSUE TITLE
Support datasources symmetric to resource blocks

### ISSUE THREAD

**Issue by nberkley-gp** [PacketFabric/terraform-provider-packetfabric#486]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We'd like to be able to reference objects created outside of Terraform in a parallel way to how we work with objects created from Terraform.

In the current provider we can only grab all of a class of resource (all cloud routers, all connections on a router, etc.) and the returned structure is very different from the structure returned when creating the same type of resource. We'd like to also be able to specify a specific resource and get back the same object we'd have gotten if we just created it via a resource block.

This is a fairly common pattern for datasource structure, see the AWS or Azure providers for examples.

### New or Affected Resource(s)

A new datasource type for each resource type.

### Potential Terraform Configuration

For example something like: 

```hcl
data "packetfabric_cloud_router_connection" "existing_connection" {
  circuit_id = "PF-L3-CUST-____"
  connection_id = "PF-L3-CON-____"
}
```
and similar for other resource types.

**Comment by rjouhann** [comment]
@nberkley-gp I should be able to get this in the next terraform version `v1.5.0` coming up tomorrow.
