### ISSUE TITLE
AWS, Azure, GCP resources & data source updates (delete/rename)

### ISSUE THREAD

**Issue by rjouhann** [PacketFabric/terraform-provider-packetfabric#50]
<img width="1073" alt="Screen Shot 2022-08-08 at 17 50 29" src="https://user-images.githubusercontent.com/25542366/183539115-ae26e111-37b5-4fb5-9292-9154ab113e0a.png">

############ AWS ############

**AWS Resources**

1. `packetfabric_cloud_services_aws_create_backbone_dedicated_cr`:  rename to `packetfabric_backbone_virtual_circuit`. The API is a bit misleading but all those resources are pointing to the same API `/v2/services/backbone` which is also documented [here](https://docs.packetfabric.com/api/v2/redoc/#tag/Services/operation/post_service_backbone).

2. `packetfabric_cloud_services_aws_req_hosted_conn`: rename to `packetfabric_cs_aws_hosted_connection` (removed the req)

3. `packetfabric_cloud_services_aws_hosted_connection`: delete? isn't a duplicate of `packetfabric_cloud_services_aws_req_hosted_conn`

4. `packetfabric_cloud_services_aws_hosted_connections`: delete (I believe this is a mistake?)

5. `packetfabric_cloud_services_aws_dedicated`: rename to `packetfabric_cs_aws_dedicated_connection`

6. `packetfabric_cloud_services_aws_hosted_marketplace`: rename to `packetfabric_cs_aws_hosted_marketplace_connection`

7. `packetfabric_cloud_services_aws_provision_requested_mkt_conn`: rename to `packetfabric_cs_aws_provision_marketplace`

**AWS Data Source**

1. `packetfabric_cloud_services_aws_connection_info`: rename to `packetfabric_cs_aws_hosted_connection`

2. `packetfabric_cloud_services_aws_dedicated_conn`: rename to `packetfabric_cs_aws_dedicated_connection`

3. `packetfabric_aws_services_hosted_requested_mkt_conn`: rename to `packetfabric_cs_aws_hosted_marketplace_connection`

############ Azure ############

**Azure Resources**

1. `packetfabric_cloud_services_azr_backbone`: delete (will be covered with renamed `packetfabric_create_backbone_virtual_circuit`)

2. `packetfabric_cloud_services_azr_req_express_conn`: rename to `packetfabric_cs_azure_hosted_connection`

3. `packetfabric_cloud_services_azr_req_express_dedicated_conn`: renamed to `packetfabric_cs_azure_dedicated_connection`

4. `packetfabric_cloud_services_azr_hosted_mkt_conn`: rename to `packetfabric_cs_azure_hosted_marketplace_connection`

5. `packetfabric_cloud_services_azr_provision_mkt`: rename to `packetfabric_cs_azure_provision_marketplace`

**Azure Data Sources**

1. `packetfabric_cloud_services_azr_connection_info`: rename to `packetfabric_cs_azure_hosted_connection`

2. `packetfabric_cloud_services_azr_dedicated_conn`:  rename to `packetfabric_cs_azure_dedicated_connection`

3. `packetfabric_azr_services_hosted_requested_mkt_conn`: rename to `packetfabric_cs_azure_hosted_marketplace_connection`

############ Google ############

**GCP Resources**

1. `packetfabric_cloud_services_gcp_backbone`: delete (will be covered with renamed `packetfabric_create_backbone_virtual_circuit`)

2. `packetfabric_cloud_services_gcp_req_hosted_conn`:rename to `packetfabric_cs_google_hosted_connection`

3. `packetfabric_cloud_services_gcp_dedicated_conn`: rename to `packetfabric_cs_google_dedicated_connection` and missing https://github.com/PacketFabric/terraform-provider-packetfabric/issues/55

4. `packetfabric_cloud_services_gcp_hosted_mkt_conn`: rename to `packetfabric_cs_google_hosted_marketplace_connection`

5. `packetfabric_cloud_services_gcp_provision_mkt`: rename to `packetfabric_cs_google_provision_marketplace`

**GCP Data Sources**

1. `packetfabric_cloud_services_gcp_connection_info`: rename to `packetfabric_cs_google_hosted_connection`

2. `packetfabric_cloud_services_gcp_dedicated_conn`: rename to `packetfabric_cs_google_dedicated_connection`

3. `packetfabric_gcp_services_hosted_requested_mkt_conn`: rename to `packetfabric_cs_google_hosted_marketplace_connection`

**Comment by rjouhann** [comment]
Created this table to help visualize options

<img width="939" alt="Screen Shot 2022-08-04 at 13 11 35" src="https://user-images.githubusercontent.com/25542366/182943663-8043f96d-5ddc-4c45-9afd-ef67cf063194.png">

**Comment by pontovinte** [comment]
This issue got solved on the current open PR.
