### ISSUE TITLE
BGP session state should not block changes

### ISSUE THREAD

**Issue by CrackerJackMack** [PacketFabric/terraform-provider-packetfabric#535]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform PacketFabric Provider Version

```
│ Error: could not retrieve bgp session
│
│   with module.pf_interconnects["us-central1"].packetfabric_cloud_router_bgp_session.session_1,
│   on ../../modules/google/hosted_interconnect/main.tf line 155, in resource "packetfabric_cloud_router_bgp_session" "session_1":
│  155: resource "packetfabric_cloud_router_bgp_session" "session_1" {
│
╵
```

`bgp_state_list` [doesn't need to be valid](https://docs.packetfabric.com/api/v2/swagger/#/Cloud%20Router%20Connections/cloud_routers_connection), especially if there are issues retrieving the BGP state.

```
    "bgp_state_list": [
        {
            "bgp_settings_uuid": "7213e293-ee59-4264-a5ee-6f5b10d19f30",
            "bgp_state": "Active"
        }
    ],
```

**Comment by rjouhann** [comment]
Hey @CrackerJackMack,

The error message seems to be related to the fact the BGP session UUID known by Terraform (and stored in the TF state file) isn't valid anymore.

The problem with BGP session is every time you update the BGP session using the `PUT`, PF will update the BGP UUID and generate a new one. If you update the BGP session outside Terraform (like through the portal), then try to update the BGP session in Terraform, the UUID stored in the state file will not match the one stored in PF and you will get the error you are seeing `Error: could not retrieve bgp session`.

It is always recommended to maintain objects created with Terraform with Terraform as TF PF provider will handle the BGP UUID update in the TF state file automatically when updating the BGP session.

As a workaround, find the BGP UUID from PF portal (look for the UUID on the BGP page) and manually update the terraform state file with the UUID, then the future TF `read()` operation  on your BGP session should succeed.

Hope this help!
Romain

**Comment by CrackerJackMack** [comment]
I made no API or Portal changes.

**Comment by rjouhann** [comment]
> I made no API or Portal changes.

I would still check if the UUID you have in your TF state file and the one on PF side match.

**Comment by CrackerJackMack** [comment]
I had a thought, since PF changes the UUID on `PUT` there could be a chance for the state file to not get updated. Maybe it's just coincidence that the two times I've encountered this issue the BGP state was still `fetching`?

**Comment by rjouhann** [comment]
I don't think the actual state of the BGP session has anything to do with this problem. When updating the BGP session with the PUT, we get the new BGP UUID from the response of the put, and set it in the state file if the change is successful (we check the CRC state for this). So if the change is successful, it will set the BGP session UUID.

https://github.com/PacketFabric/terraform-provider-packetfabric/blob/main/internal/provider/resource_bgp_session.go#L366

We would have to look in cyberdyne/HAL log to track the different BGP session changes and see how the BGP session UUID changed and differ from the TF state file. I don't have access as you know but @AndreasSteinerPF can probably help :)

**Comment by CrackerJackMack** [comment]
If it happens again I'll reopen this

**Comment by CrackerJackMack** [comment]
API timeouts leave it in this state as well
```
╷
│ Error: Put "https://api.packetfabric.com/v2/services/cloud-routers/PF-L3-CUST-1716200/connections/PF-L3-CON-1781663/bgp": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
│
│   with module.pf_interconnects["us-central1"].packetfabric_cloud_router_bgp_session.session_0,
│   on ../../modules/google/hosted_interconnect/main.tf line 137, in resource "packetfabric_cloud_router_bgp_session" "session_0":
│  137: resource "packetfabric_cloud_router_bgp_session" "session_0" {
│
╵
```

resulting in inability to plan without manual state manipulation.

```
Plan: 0 to add, 4 to change, 0 to destroy.
╷
│ Error: could not retrieve bgp session
│
│   with module.pf_interconnects["us-central1"].packetfabric_cloud_router_bgp_session.session_0,
│   on ../../modules/google/hosted_interconnect/main.tf line 137, in resource "packetfabric_cloud_router_bgp_session" "session_0":
│  137: resource "packetfabric_cloud_router_bgp_session" "session_0" {
│
╵
```

**Comment by AndreasSteinerPF** [comment]
The release with this change went out yesterday, so updating the BGP Session no longer changes their UUID, which should solve these issues.
