### ISSUE TITLE
make test fails on all branches

### ISSUE THREAD

**Issue by medzin** [PacketFabric/terraform-provider-packetfabric#58]
`make test` fails on all branches `feature/google-service`. Below is the command and the error message:

```
make test
go test -i $(go list ./... | grep -v 'vendor') || exit 1
tools/tools.go:5:2: import "github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs" is a program, not an importable package
```

**Comment by pontovinte** [comment]
The UTs are expected to run on client level only. Please see the output below:

`yrineu@pontovinte:~/pontovinte/plugin/terraform-provider-packetfabric/internal/packetfabric [feature/google-service|!?] $ go test
PASS
ok      github.com/PacketFabric/terraform-provider-packetfabric/internal/packetfabric   0.013s
`

**Comment by rjouhann** [comment]
@medzin  could you review PR https://github.com/PacketFabric/terraform-provider-packetfabric/pull/82. Feel free to reopen this issue if not fixed.
