### ISSUE TITLE
Missing usage example for cloud_services_aws_create_backbone_dedicated_cr resource

### ISSUE THREAD

**Issue by medzin** [PacketFabric/terraform-provider-packetfabric#6]
`cloud_services_aws_create_backbone_dedicated_cr` is missing usage example:

https://github.com/PacketFabric/terraform-provider-packetfabric/blob/dev/docs/resources/cloud_services_aws_create_backbone_dedicated_cr.md#example-usage

**Comment by elXaptation** [comment]
Will update/provide with completion of #9
