### ISSUE TITLE
packetfabric_cs_azure_hosted_connection: json: cannot unmarshal string into Go struct field

### ISSUE THREAD

**Issue by rjouhann** [PacketFabric/terraform-provider-packetfabric#64]
Using:
```
# From the PacketFabric side: Create a PacketFabric Hosted Cloud Connection.
resource "packetfabric_cs_azure_hosted_connection" "cs_conn1" {
  provider          = packetfabric
  description       = "${var.tag_name}-${random_pet.name.id}"
  account_uuid      = var.pf_account_uuid
  azure_service_key = azurerm_express_route_circuit.azure_express_route_1.service_key
  port              = var.pf_port_circuit_id
  speed             = var.pf_cs_speed # will be deprecated
  vlan_private      = var.pf_cs_vlan_private
  #vlan_microsoft = var.pf_cs_vlan_microsoft
}
```

With those variables: (set your own account_uuid and azure_service_key)
```
# Azure Hosted Connection
variable "pf_port_circuit_id" {
  type    = string
  default = "PF-AP-WDC1-1726464" # replace with a port you have created in your account
}
variable "pf_cs_speed" {
  type    = string
  default = "50Mbps"
}
variable "pf_cs_vlan_private" {
  type    = number
  default = 100
}
variable "pf_cs_vlan_microsoft" {
  type    = number
  default = 101
}
```

Getting this error:
```
packetfabric_cs_azure_hosted_connection.cs_conn1: Still creating... [10s elapsed]
╷
│ Error: json: cannot unmarshal string into Go struct field AzureComponents.components.ifd_port_circuit_id_cust of type int
│ 
│   with packetfabric_cs_azure_hosted_connection.cs_conn1,
│   on main.tf line 91, in resource "packetfabric_cs_azure_hosted_connection" "cs_conn1":
│   91: resource "packetfabric_cs_azure_hosted_connection" "cs_conn1" {
│ 
╵
```

**Comment by pontovinte** [comment]
Hi @rjouhann, I believe there's a discrepancy between docs and the API. Since we're relying on docs as our source of truth, it shows both `ifd_port_circuit_id_cust` and `ifd_port_circuit_id_pf` with `int` values.

![image](https://user-images.githubusercontent.com/72367088/185830803-1fc34f66-23d7-4e4d-8197-3fd2caef3186.png)

Please see this link for reference (https://docs.packetfabric.com/api/v2/redoc/#tag/Cloud-Services-Azure/operation/azure_hosted_connection_post)

**Comment by rjouhann** [comment]
Hey @pontovinte, in the link you shared, the `port` is a string, not an `int`.

_port | required | string The port to connect to Azure._

Example: `"port": "PF-AP-LAX1-1002",`

**Comment by pontovinte** [comment]
@rjouhann, either `port` is `string` ([here](https://github.com/PacketFabric/terraform-provider-packetfabric/pull/39/files#diff-9851bb53abbfffc4f33a4f1b4e317ba2d6fe20d46314c07a8af90093097c4e1bR129)) and `ifd_port_circuit_id_cust` is `int` ([here](https://github.com/PacketFabric/terraform-provider-packetfabric/pull/39/files#diff-9851bb53abbfffc4f33a4f1b4e317ba2d6fe20d46314c07a8af90093097c4e1bR156)). The issue above was complaining about `ifd_port_circuit_id_cust` not being parsed correctly. But I'm confused if there's any discrepancy between API doc and the actual API as I explained [here](https://github.com/PacketFabric/terraform-provider-packetfabric/issues/64#issuecomment-1221739485)

**Comment by rjouhann** [comment]
@pontovinte I understand the confusion the `ifd_port_circuit_id_cust` and `ifd_port_circuit_id_pf` are part of the API response, not the body of the request.

To my knowledge and understanding, ports which is part of the body of the request is always a string because there is always a prefix and PoP name like `PF-AP-LAX-1234` and sometime a suffix like `PF-AP-LAX-1234-PF`.

I actually tried to create a connection using `/services/cloud/hosted/azure` and look what I am getting in the response:

```
    "components": {
        "ifd_port_circuit_id_cust": "PF-AP-LAX2-1729130",
```

`ifd_port_circuit_id_cust` is a string. I will follow up with PF dev team and get the API schema more clear so it says `ifd_port_circuit_id_cust` and `ifd_port_circuit_id_pf` are `string`, not `int`.

**Comment by rjouhann** [comment]
Verified fix in [feature/google-service](https://github.com/PacketFabric/terraform-provider-packetfabric/tree/feature/google-service) branch
