### ISSUE TITLE
packetfabric_cs_aws_dedicated_connection data source does not exist

### ISSUE THREAD

**Issue by rjouhann** [PacketFabric/terraform-provider-packetfabric#72]
`packetfabric_cs_aws_dedicated_connection` data source does not exist, see error below.

We used to have [cloud_services_aws_dedicated_conn ](https://registry.terraform.io/providers/PacketFabric/packetfabric/latest/docs/data-sources/cloud_services_aws_dedicated_conn) which should be the same data source so maybe the rename did not happen part of https://github.com/PacketFabric/terraform-provider-packetfabric/issues/50?

```
│ Error: Invalid data source
│ 
│   on main.tf line 111, in data "packetfabric_cs_aws_dedicated_connection" "pf_cs_conn1":
│  111: data "packetfabric_cs_aws_dedicated_connection" "pf_cs_conn1" {
│ 
│ The provider terraform.local/packetfabric/packetfabric does not support data source
│ "packetfabric_cs_aws_dedicated_connection".
│ 
│ Did you intend to use the managed resource type "packetfabric_cs_aws_dedicated_connection"? If so, declare this using a
│ "resource" block instead of a "data" block.
╵
```

Terraform config"
```
data "packetfabric_cs_aws_dedicated_connection" "pf_cs_conn1" {
  provider = packetfabric
}
output "packetfabric_cs_aws_dedicated_connection" {
  value = data.packetfabric_cs_aws_dedicated_connection.pf_cs_conn1
}
```

**Comment by elXaptation** [comment]
This looks like a type related issue:

[https://github.com/PacketFabric/terraform-provider-packetfabric/blob/feature/google-service/internal/provider/provider.go](url)
`		DataSourcesMap: map[string]*schema.Resource{
			"packetfabric_cloud_router":                            dataSourceCloudRouter(),
			"packetfabric_cloud_router_bgp_prefixes":               dataSourceBgpPrefix(),
			"packetfabric_aws_cloud_router_connection":             dataSourceCloudConn(),
			"packetfabric_cloud_router_bgp_session":                dataSourceBgpSession(),
			"packetfabric_cs_aws_hosted_connection":                dataSourceCloudServicesConnInfo(),
			"packetfabric_cs_aws_dedicated_connection_conn":        datasourceDedicatedConn(), <<<<<<<<<<
`

**Comment by rjouhann** [comment]
Let's also move this on for v0.3.0 (as this is data source related to this bug https://github.com/PacketFabric/terraform-provider-packetfabric/issues/71 pushed to v0.3.0)

**Comment by rjouhann** [comment]
Linked to https://github.com/PacketFabric/terraform-provider-packetfabric/issues/84
