### ISSUE TITLE
Rename packetfabric_interface to packetfabric_port

### ISSUE THREAD

**Issue by rjouhann** [PacketFabric/terraform-provider-packetfabric#75]
Discussed with PF UX and also looked at the [API](https://docs.packetfabric.com/api/v2/redoc/#tag/Ports/operation/port_post) and [doc](https://docs.packetfabric.com/ports/), we should not call this resource and data source  `packetfabric_interface` but `packetfabric_port` so it's more coherent and we don't introduce a new name.

Make sure we also update the variable names in the examples: `pf_interface_pop1` to `pf_port_pop1`

**Comment by rjouhann** [comment]
@pontovinte  @elXaptation for visibility

**Comment by rjouhann** [comment]
@freeform700  for visibility

**Comment by pontovinte** [comment]
Just pushed a new patch renaming this resource.

**Comment by rjouhann** [comment]
@pontovinte  let's keep it open so the doc can also be updated @elXaptation

**Comment by elXaptation** [comment]
This issue is covered in #87 from a documentation side. I believe we're ready to close.
