### ISSUE TITLE
packetfabric_backbone_virtual_circuit delete isn't working

### ISSUE THREAD

**Issue by rjouhann** [PacketFabric/terraform-provider-packetfabric#76]
The `packetfabric_outbound_cross_connect` delete isn't using the correct API.

It should be using: `DELETE /v2/services/{vc_circuit_id}` (https://docs.packetfabric.com/api/v2/swagger/#/Services/delete_service)

Creation works fine but return this error:
```
╷
│ Error: Status: 404, body: {"message": "Cloud not found: PF-BC-PDX-NYC-1743975-PF", "request_id": "f03bd549-e87b-4195-9580-7dd597b6b85a"}
│ 
│ 
```

I think this is related to the renaming https://github.com/PacketFabric/terraform-provider-packetfabric/issues/50.

`packetfabric_cloud_services_aws_create_backbone_dedicated_cr`: rename to `packetfabric_backbone_virtual_circuit`. 
The API is a bit misleading but all those resources are pointing to the same API /v2/services/backbone which is also documented [here](https://docs.packetfabric.com/api/v2/redoc/#tag/Services/operation/post_service_backbone).

**Comment by pontovinte** [comment]
What about [this](https://docs.packetfabric.com/api/v2/redoc/#tag/Outbound-Cross-Connects/operation/outbound_cross_connect_delete) API?

**Comment by rjouhann** [comment]
I already had open one for this issue https://github.com/PacketFabric/terraform-provider-packetfabric/issues/70
