### ISSUE TITLE
Missing usage example for cloud_services_aws_req_hosted_conn resource

### ISSUE THREAD

**Issue by medzin** [PacketFabric/terraform-provider-packetfabric#8]
`cloud_services_aws_req_hosted_conn` resource is missing usage example:

https://github.com/PacketFabric/terraform-provider-packetfabric/blob/dev/docs/resources/cloud_services_aws_req_hosted_conn.md#example-usage

**Comment by elXaptation** [comment]
Will update/provide with completion of #9
